basePath: /app/expense
definitions:
  querymodel.CategoryAll:
    properties:
      pageToken:
        type: string
      sort:
        type: string
      status:
        type: string
    type: object
  requestmodel.IncomeBodyCreate:
    properties:
      category:
        type: string
      money:
        type: number
      note:
        type: string
    type: object
  requestmodel.IncomeBodyUpdate:
    properties:
      category:
        type: string
      money:
        type: number
      note:
        type: string
    type: object
  requestmodel.UserBodyLogin:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  requestmodel.UserBodyRegister:
    properties:
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  responsemodel.ResponseCreate:
    properties:
      _id:
        type: string
    type: object
info:
  contact:
    email: tuanngo.472000@gmail.com
    name: Dev team
  description: |
    All APIs for Expense app.

    ******************************
    - Add description
    ******************************
  title: Expense Tracker - App API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      operationId: app-category-all
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/querymodel.CategoryAll'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: All
      tags:
      - Category
  /incomes:
    post:
      consumes:
      - application/json
      operationId: create-income-money
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.IncomeBodyCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Income
  /incomes/{id}:
    put:
      consumes:
      - application/json
      operationId: update-income-money
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.IncomeBodyUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Income
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
  /users/login:
    post:
      consumes:
      - application/json
      operationId: user-login
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.UserBodyLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login
      tags:
      - User
  /users/me:
    get:
      consumes:
      - application/json
      operationId: user-get-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: GetMe
      tags:
      - Staff
  /users/register:
    post:
      consumes:
      - application/json
      operationId: user-register
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.UserBodyRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Register
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
