basePath: /app/expense
definitions:
  requestmodel.IncomeMoneyBodyCreate:
    properties:
      category:
        type: string
      money:
        type: number
      note:
        type: string
    type: object
  requestmodel.IncomeMoneyBodyUpdate:
    properties:
      category:
        type: string
      money:
        type: number
      note:
        type: string
    type: object
  requestmodel.UserBodyLogin:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  requestmodel.UserBodyRegister:
    properties:
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  responsemodel.ResponseCreate:
    properties:
      _id:
        type: string
    type: object
  responsemodel.ResponseUpdate:
    properties:
      _id:
        type: string
    type: object
info:
  contact:
    email: tuanngo.472000@gmail.com
    name: Dev team
  description: |
    All APIs for Expense app.

    ******************************
    - Add description
    ******************************
  title: Expense Tracker - App API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      operationId: app-category-all
      parameters:
      - in: query
        name: pageToken
        type: string
      - in: query
        name: sort
        type: string
      - in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - Category
  /income-moneys:
    get:
      consumes:
      - application/json
      operationId: app-income-money-all
      parameters:
      - in: query
        name: fromAt
        type: string
      - in: query
        name: pageToken
        type: string
      - in: query
        name: sort
        type: string
      - in: query
        name: toAt
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - IncomeMoney
    post:
      consumes:
      - application/json
      operationId: app-income-money-create
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.IncomeMoneyBodyCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - IncomeMoney
  /income-moneys/{id}:
    get:
      consumes:
      - application/json
      operationId: app-income-money-detail
      parameters:
      - description: Income money id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Detail
      tags:
      - IncomeMoney
    put:
      consumes:
      - application/json
      operationId: app-income-money-update
      parameters:
      - description: Income money id
        in: path
        name: id
        required: true
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.IncomeMoneyBodyUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseUpdate'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - IncomeMoney
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
  /users/login:
    post:
      consumes:
      - application/json
      operationId: user-login
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.UserBodyLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login
      tags:
      - User
  /users/me:
    get:
      consumes:
      - application/json
      operationId: user-get-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: GetMe
      tags:
      - Staff
  /users/register:
    post:
      consumes:
      - application/json
      operationId: user-register
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.UserBodyRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Register
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
