basePath: /admin/expense
info:
  contact:
    email: tuanngo.472000@gmail.com
    name: Dev team
  description: |
    All APIs for Expense admin.

    ******************************
    - Add description
    ******************************
  title: Expense Tracker - Admin API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
