basePath: /admin/expense
definitions:
  ptime.TimeResponse:
    properties:
      time:
        type: string
    type: object
  requestmodel.CategoryBodyCreate:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  requestmodel.CategoryBodyUpdate:
    properties:
      name:
        type: string
    type: object
  requestmodel.CategoryChangeStatus:
    properties:
      status:
        type: string
    type: object
  responsemodel.ResponseCategoryAdmin:
    properties:
      _id:
        type: string
      createdAt:
        $ref: '#/definitions/ptime.TimeResponse'
      name:
        type: string
      status:
        type: string
      type:
        type: string
      updatedAt:
        $ref: '#/definitions/ptime.TimeResponse'
    type: object
  responsemodel.ResponseCategoryAll:
    properties:
      limit:
        type: integer
      list:
        items:
          $ref: '#/definitions/responsemodel.ResponseCategoryAdmin'
        type: array
      total:
        type: integer
    type: object
  responsemodel.ResponseChangeStatus:
    properties:
      _id:
        type: string
      status:
        type: string
    type: object
  responsemodel.ResponseCreate:
    properties:
      _id:
        type: string
    type: object
  responsemodel.ResponseUpdate:
    properties:
      _id:
        type: string
    type: object
info:
  contact:
    email: tuanngo.472000@gmail.com
    name: Dev team
  description: |
    All APIs for Expense admin.

    ******************************
    - Add description
    ******************************
  title: Expense Tracker - Admin API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      operationId: category-all
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: status
        type: string
      - in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCategoryAll'
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - Category
    post:
      consumes:
      - application/json
      operationId: category-create
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryBodyCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Category
  /categories/{id}:
    get:
      consumes:
      - application/json
      operationId: category-detail
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCategoryAdmin'
      security:
      - ApiKeyAuth: []
      summary: Detail
      tags:
      - Category
    put:
      consumes:
      - application/json
      operationId: category-update
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryBodyUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseUpdate'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - Category
  /categories/{id}/status:
    patch:
      consumes:
      - application/json
      operationId: category-change-status
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryChangeStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseChangeStatus'
      security:
      - ApiKeyAuth: []
      summary: ChangeStatus
      tags:
      - Category
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
